NAME = 'Route animation from Garmin Fenix 6.'
PATH_COLOR = 'bf00aaff'
LINE_WIDTH = 5
CAMERA_HEADING = 0
CAMERA_TILT = 60
CAMERA_RANGE = 2000
ANIMATION_DELAY = 0.02
ALTITUDE = 0
ALTITUDE_MODE = 'relativeToGround'
# relativeToGround, absolute, relativeToSeaFloor, clampToGround, clampToSeaFloor
# https://developers.google.com/kml/documentation/cameras
TOTAL_ROTATION = 120

LOOK_ALTITUDE = 0
CITY_FLIGHT_DURATION = 1
CITY_PAUSE_DURATION = 1
CITY_FLY_MODE = 'smooth'
START_ALTITUDE_CITIES = 10000000
LOOK_ALTITUDE_CITIES = 1000000
CAMERA_HEADING_CITIES = 0
CAMERA_TILT_CITIES = 0
CAMERA_RANGE_CITIES = 1000000
CITY_TOUR_INITIAL_DELAY = 0
ALTITUDE_MODE_CITIES = 'absolute'
CITY_NAME = '2022 World Tour'
TOTAL_ID_POINTS = 101
